sudo: required
language: ruby
services:
- docker
script:
- ls -lah
- docker build -f Dockerfile -t apsl/rundeck .
notifications:
  email:
  - sistemas@apsl.net
env:
  global:
  - RUNDECK_VERSION=2.6.0b
  - secure: ZN7wvienYdiW4UXz8YkQHhlGqnkGujn3vwJg8eqtXSBZQOqKTkUgujinvHfOaCY4VWhQ3NRQ0YlAC432e9XkjeIhBYA5v2PFEPiOAOYAVKnfcq5fAaEaeOw30wrlSJW2xYMYqZdQWl5DBTO8x699agkLjukOJOno9Wh41GP2Iuw0dGR3AlEznDD1ciutqZeLdfr0sncEo1PCTfHhT44gBjjJ22yzvxiZT0ETswcXHKWSA2LAow/ejsCLDpcfuc9sps1irO42hHaOmuBbbS0SxSUiIuzpi2F9F5oqIC60E7kLeIY5DXamfnvYSBfyRaKQX83O+HMHbqiqdHNihNi6PEuENeuBPbt3g6VypPvs/ftgmmulTI8pXMdtBuaniFGLNBW96tt/jhAFr93ji0hYkac+Xdtu59xnX1uYKEGVlc9Cp6ZyqxJF39rGzddJeB6TQifDxBayFcegX1PxHvuezX38ivfx6f6ZZV28EwHX9IjmXyFLgAtCbaceNMmQAVBTTztPiCCuLpe3gJSLNPmOYRJYiMG0ozysq1yfNh3gieMOeaFInsYjKC/dALLhlaInQzuLjNJ4RRSluZ5H8pO16ihf1rfbrnOsJ8uIVHa5GlJ8/eQed8mCKYm46fLWsmxp+FYYJfMFX//5Aya8I+p4YvUYtTDsGliFJbNOn12ZA6Y=
  - secure: d22hsXcWZjIzb6BNxyHOoqRmizkZ7mPcMIfqWBWZz7wUmbc6p3UiKRddShrixIJMTmwpkyQRs7kfBIH7DxS77aF/UzvUwpGJV4J5Z1kLbqjIm0g/6t61CAjBal/oxSQMhVYamdhuE3xd6O9pGi6beg5wmPOY5GPP8+lb4cj9gjIDum4Tf2AyOR3XJDHMjWogUAOY0u7RTKivnHEwHj/O5lq7qKQ65P6L/l6u52NrEeKglFz6iTzJ4J+8s9VTtqxium1E8u2uPWEGXZQaZ52CDF486UhCtDBobXWKOYvtaEMZRJ4tyjHugonB5p00Bf2hU6J4XX60iczg+y+sJNXuUKgoVRraT9forPtrT9eOnQ3WnVVpeC0fV5tp66E5Mdi1jKLqFA47bIw1TmqaPcjlzxaSkjsVlCXJ+6N4ctJkHcPjqKkLs2EaeoEK1UBCGvtfVoQxXZhrV0CIkVUEm+oxzJphNC1c8dKMKqD+6sUV2KgLXbL4pKJP2hAYwpgsJzSOFUsm3S6KjqqBaw11w5wyip0gFnk/5IrvX5t+xBhRWpT3lNAimw86NX+exYQE+Yyq8xP+0tAmI5Efd63oTvAhLfYiVsEDYCxkZz6/oxnWXzhnM2aDv2YXPH1WlMwh7gHgW7axgweeWa0LW2tobG3Ze/kFiKyW3lrinKGEtNZta/I=
  - secure: gLja1AQo4tcsH63MTga9Zlzuzk8tlC0mArcftRJ0yLxasrGm9dRvN7OP8zWukPLqJRfeNUqTPAJ/9vJGdSVNQonTPfy2xyuJ5xGkxEYXV5tuUo+4c8TqdYKnWrwhl34Q5FegmgHTBg8cVsbx8TnO87YYxwdJMWYExmAgwUwnQFOV2BSYam/Fs8GIZYCuFEJjR7/lfsUuIMiVAAAvnpuXd2o7lwDTk5A3IzhRx53MeT1QZ3mijNc3/KSYqjjkuoEPUKaHcViRWgIxGiRwpB2yohYAQNrb0PJV1IfUgA2RXjqt7WoYdQZhmDxigrOfYo7LfZNbmnqwPoikZLf0hMT22+4DxiUq4p7Y1vGMk+Zmhtp8Sy0NBXVbsGFK4FcSROelIIH3J086IEqVnm4jrfaX2YbUTC2dPUvZcqQIkK8oIc3PuGeZiQG6b/kM2W+RtmhPkjNUoHBqSHvZ0KWPYzzDlu0K5fsmyDYrfEFNgts1rs6jiFwpIDW+b/bKmOuJQgoPf9aGwfhwcx1eY1mITibkrPq+UhzQi3hMZ68Mhxjy94NGm48OgBX5jXcWj7Yke/Pz/RwI7tI+4N1pUeOcLl021ur0wSPaDJUrxK3mcaz6MAoUIGlGYiF74UVCxdnBK+ej++5qcyBxeFZIadOVQCVrvVXxn2TpZ4W6fheie575KrM=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=$RUNDECK_VERSION
- docker tag -f apsl/rundeck apsl/rundeck:$TAG
- docker push apsl/rundeck:$TAG 
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag -f apsl/rundeck apsl/rundeck:latest; docker push apsl/rundeck:latest; fi
