web:
  build: .
  environment:
    RUNDECK_DATABASE_ENGINE: postgresql
    RUNDECK_INITIAL_ADMIN_PASSWORD: holaquetal
    RUNDECK_SERVER_URL: http://rundeck.mydomain.com
    RUNDECK_POSTGRES_HOST: postgres
    RUNDECK_POSTGRES_DATABASE: rundeckdb
    RUNDECK_POSTGRES_USER: urundeck
    RUNDECK_POSTGRES_PASSWORD: rundeckpass
    RUNDECK_MAIL_HOST: smtp.mail.com
    RUNDECK_MAIL_USERNAME: username
    RUNDECK_MAIL_PORT: 587
    RUNDECK_MAIL_PASSWORD: passs
    RUNDECK_MAIL_STARTTLS: true
    RUNDECK_MAIL_SMTP_AUTH: true
    RUNDECK_MAIL_DEFAULT_FROM: norepy@domain.com
  volumes:
    - ./volumes/data:/data
  links:
    - "postgres:postgres"
  ports:
    - "0.0.0.0:8012:4440"
postgres:
  image: apsl/postgres:latest
  environment:
    POSTGRES_DB: rundeckdb
    POSTGRES_USER: urundeck
    POSTGRES_PASSWORD: rundeckpass
    #POSTGRESQL_ROOT_PASSWORD: ashoNg0aloqu2oh
    PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
    - "./data:/var/lib/postgresql/data"
